### ISSUE TITLE
SMD transistor symbol/connection

### ISSUE THREAD

**Issue by muellni** [marove2000/OwlThief#1]
Thanks for this awesome assembly kit. During creation of my SMD-only fork I noticed that the symbol of the SMD transistor `Q_b1` is `Device:Q_NPN_CBE` which in connection with the footprint `Package_TO_SOT_SMD:SOT-23` will lead to a wrong connected transistor.  At least for the transistors I found, like BC 847. The all seem to have the following pinout: 
![image](https://github.com/marove2000/OwlThief/assets/569476/e0f3dd60-47ec-4a77-91ff-500ef0dd6007)

I suggest you change the symbol to `Device:Q_NPN_BEC`  which should have the correct pin order.

**Comment by marove2000** [comment]
Hi muellni,

thanks for the hint! I've just updated the PCB. v1.2 will have the fix!
